version: 2.1
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@4.1
  twilio: circleci/twilio@1.0.0
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: "echo environment variables from org-global context"
          command: echo ${SLACK_ACCESS_TOKEN}
      - run:
          name: Install dependencies
          command: npm install
      - run: npm run test
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always
      - twilio/install
      - twilio/sendsms:
          body: This is a custom message notification
          from: '${TWILIO_FROM}'
          to: '${TWILIO_TO}'
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify:
          context: slackIntergration