version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm run test
workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify